before_install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y "deb http://cran.r-project.org/bin/linux/ubuntu $(lsb_release -cs)/" > /dev/null 2>&1
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 > /dev/null 2>&1
  - sudo add-apt-repository -y "ppa:marutter/rrutter" > /dev/null 2>&1
  - sudo add-apt-repository -y "ppa:marutter/c2d4u" > /dev/null 2>&1
  - sudo add-apt-repository -y "ppa:texlive-backports/ppa" > /dev/null 2>&1
  - sudo apt-get -qq update
install:
  - sudo apt-get --no-install-recommends -qq install r-base-dev r-recommended qpdf pandoc pandoc-citeproc
  - sudo apt-get --no-install-recommends -qq install lmodern texinfo texlive-base texlive-extra-utils texlive-fonts-extra texlive-fonts-recommended texlive-generic-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended
  - sudo apt-get -qq install r-cran-{jsonlite,httr,lubridate,plyr,shiny,knitr,rmarkdown,testthat}
before_script:
  - echo 'options(repos = c(CRAN = "http://cran.r-project.org"))' | sudo tee -a /etc/R/Rprofile.site > /dev/null
  - Rscript -e 'sessionInfo()'
  - PKGNAME=$(grep 'Package:' DESCRIPTION | cut -d ':' -f 2 | tr -d ' ')
  - PKGVER=$(grep 'Version:' DESCRIPTION | cut -d ':' -f 2 | tr -d ' ')
  - PKGDIR=${PWD}
  - cd ..
  - rm -f *.tar.gz
  - R CMD build ${PKGDIR}
script:
  - R CMD check ${PKGNAME}_${PKGVER}.tar.gz --as-cran
after_script:
  - rm -f ${PKGNAME}_${PKGVER}.tar.gz
  - ! grep -q -R "WARNING" ${PKGNAME}.Rcheck/00check.log
